feat: Bump cloudposse-s3-log-storage version
lablabs/terraform-aws-session-manager-logs pull request #6
Opened 2023-06-14 12:54 UTC by Balsir

# Description

Bump version to enable first-try bucket creation. Recommended configuration requires ACL (therefore, ACL creation shouldn't be disabled.

## Type of change

- [ ] A bug fix (PR prefix `fix`)
- [ ] A new feature (PR prefix `feat`)
- [ ] A code change that neither fixes a bug nor adds a feature (PR prefix `refactor`)
- [ ] Adding missing tests or correcting existing tests (PR prefix `test`)
- [ ] Changes that do not affect the meaning of the code like white-spaces, formatting, missing semi-colons, etc. (PR prefix `style`)
- [ ] Changes to our CI configuration files and scripts (PR prefix `ci`)
- [ ] Documentation only changes (PR prefix `docs`)

## How Has This Been Tested?

2023-06-16 07:05 UTC, dojci requested changes
Please fix the failing pipeline or renovate actions

2023-06-19 13:25 UTC, Balsir commented
Tested in tf-org, plan adds expected resource, because versioning is disabled:
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the
following symbols:
  + create

Terraform will perform the following actions:
````shell
  # module.ssm_session_log.module.ssm-bucket.module.aws_s3_bucket.aws_s3_bucket_versioning.default[0] will be created
  + resource "aws_s3_bucket_versioning" "default" {
      + bucket = "ref-management-ssm"
      + id     = (known after apply)

      + versioning_configuration {
          + mfa_delete = (known after apply)
          + status     = "Suspended"
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.
````

2023-06-20 17:40 UTC, dojci requested changes

2023-06-20 17:40 UTC, dojci commented on variables.tf
> +# tflint-ignore: terraform_unused_declarations
Please remove all unused values

2023-06-20 17:59 UTC, dojci approved these changes
LGTM

2023-06-22 12:48 UTC, merged